#!/bin/bash

if [[ $# < 1 || $1 == -* ]]
then
    echo "Cenzhe's script to new python file"
    echo "Usage: $0 filename"
elif [[ -e $1.py ]]
then
    echo "$1.py already exists, skipping file creation..."
else
    cat <<EOF > $1.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
# Author: ZHU Cenzhe, Davy
# Email: cenzhe.zhu@gmail.com
# Description: 
EOF
    echo "# Creation time: $(date)" >> $1.py
    cat <<EOF >> $1.py

if __name__ == '__main__':
    pass

EOF
fi

