#!/bin/bash

if [[ $# < 1 || $1 == -* ]]
then
    echo "Cenzhe's script to new python file"
    echo "Usage: $0 filename"
elif [[ -e $1.py ]]
then
    echo "$1.py already exists, skipping file creation..."
else
    echo '#!/usr/bin/python' > $1.py
    echo '# -*- coding: utf-8 -*-' >> $1.py
    echo '# Author: ZHU Cenzhe, Davy' >> $1.py
    echo '# Email: cenzhe.zhu@gmail.com' >> $1.py
    echo "# Creation time: `date`" >> $1.py
    echo "" >> $1.py
fi

